apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-worker
  namespace: shopx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-worker
  template:
    metadata:
      labels:
        app: order-worker
    spec:
      containers:
        - name: order-worker
          image: ghcr.io/egortarasov/k8s-hw/order-worker:dev
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: order-worker
            - secretRef:
                name: order-worker
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi