apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: shopx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: ghcr.io/egortarasov/k8s-hw/auth-service:dev
          imagePullPolicy: Always
          ports:
            - name: grpc
              containerPort: 9090
          envFrom:
            - configMapRef:
                name: auth-service
            - secretRef:
                name: auth-service
          readinessProbe:
            tcpSocket:
              port: grpc
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: grpc
            periodSeconds: 10
            failureThreshold: 6
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi